"""baseline schema ตาราง 3.9-3.14 พร้อม expires_at

Revision ID: 33221256467d
Revises: 
Create Date: 2026-09-22 15:51:57.810291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33221256467d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_model',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('train_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('email',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('receive_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_hash', sa.String(length=255), nullable=False),
    sa.Column('body_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('email_id')
    )
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_body_hash'), ['body_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_expires_at'), ['expires_at'], unique=False)

    op.create_table('detection_result',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('phishing_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('scan_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.email_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['detection_model.model_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    with op.batch_alter_table('detection_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_result_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_result_model_id'), ['model_id'], unique=False)

    op.create_table('feature_vector',
    sa.Column('vector_id', sa.Uuid(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=True),
    sa.Column('feature_value', sa.Double(), nullable=True),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.email_id'], ),
    sa.PrimaryKeyConstraint('vector_id')
    )
    with op.batch_alter_table('feature_vector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_vector_email_id'), ['email_id'], unique=False)

    op.create_table('tokenized_word',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.email_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('tokenized_word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenized_word_email_id'), ['email_id'], unique=False)

    op.create_table('tfidf_feature',
    sa.Column('tfidf_id', sa.Uuid(), nullable=False),
    sa.Column('tf_value', sa.Double(), nullable=True),
    sa.Column('idf_value', sa.Double(), nullable=True),
    sa.Column('tfidf_score', sa.Double(), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokenized_word.token_id'], ),
    sa.PrimaryKeyConstraint('tfidf_id')
    )
    with op.batch_alter_table('tfidf_feature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tfidf_feature_token_id'), ['token_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tfidf_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tfidf_feature_token_id'))

    op.drop_table('tfidf_feature')
    with op.batch_alter_table('tokenized_word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenized_word_email_id'))

    op.drop_table('tokenized_word')
    with op.batch_alter_table('feature_vector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_vector_email_id'))

    op.drop_table('feature_vector')
    with op.batch_alter_table('detection_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_result_model_id'))
        batch_op.drop_index(batch_op.f('ix_detection_result_email_id'))

    op.drop_table('detection_result')
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_expires_at'))
        batch_op.drop_index(batch_op.f('ix_email_body_hash'))

    op.drop_table('email')
    op.drop_table('detection_model')
    # ### end Alembic commands ###
